mdapi/objects/Elevated_Access_Request__c.object
<CustomObject>
    <label>Elevated Access Request</label>
    <nameField>
        <displayFormat>EAR-{0000000000}</displayFormat>
        <label>Elevated Access Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elevated Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>Current_Profile_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Current Profile ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>For_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>For User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Elevated_Access_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

mdapi/classes/RevertElevatedAccess.cls
public class RevertElevatedAccess {
    @InvocableMethod(label='Update user to previous Profile for list of UserIDs' description='Update user to previous Profile for list of UserIDs')
    public static void updateToPreviousProfile(List<ID> ids) {
        System.Debug('***** IDs: ' + ids);
        for (Elevated_Access_Request__c ear : [select For_User__c, Current_Profile_ID__c from Elevated_Access_Request__c where id = :ids]) {
            doActualUserProfileUpdate(ear.For_User__c, ear.Current_Profile_ID__c);
        }

        return;
    }
    
    @future
    public static void doActualUserProfileUpdate(ID uid, ID pid) {
        System.Debug('Updating User ' + uid + ' with Profile ' + pid);
        User u = new User();
        u.id = uid;
        u.profileid = pid;
        update u;
	}    
}