mdapi/objects/Elevated_Access_Request__c.object
<CustomObject>
    <label>Elevated Access Request</label>
    <nameField>
        <displayFormat>EAR-{0000000000}</displayFormat>
        <label>Elevated Access Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Elevated Access Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <fields>
        <fullName>For_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>For User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Elevated_Access_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Date__c</fullName>
        <defaultValue>NOW() + (0.04167 * 4)</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>From Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Saved</fullName>
                    <default>true</default>
                    <label>Saved</label>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Access Provided</fullName>
                </value>
                <value>
                    <fullName>Access Reverted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>To_Date__c</fullName>
        <defaultValue>NOW() + (0.04167 * 8)</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>To Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
</CustomObject>

force-app/main/default/classes/BlockElevatedAccessEventCondition.cls
global class BlockElevatedAccessEventCondition implements TxnSecurity.EventCondition {
    
    public boolean evaluate(SObject event) {
        switch on event {
            when LoginEvent loginEvent {
                return evaluate(loginEvent);
            }
            when null {
                return false;   
            }
            when else{
                return false;
            }
        }
    }
    
    private boolean evaluate(LoginEvent loginEvent) {
        User u = [SELECT Id, Profile.Name, UserName FROM User WHERE Id = :loginEvent.UserId];
        
        if (u != null) {
            // Ensure we are not blocking out every System Admin. Ensure couple of power users can always access the system 
            if ( u.UserName == 'venkatramans@dummyco.com.acctpoc' ) return false;
            
            if ( u.UserName != 'venkatramans@dummyco.com.acctpoc' && 
                u.Profile.Name == 'System Administrator' ) {
                    datetime currentTime = datetime.now();
                    System.Debug('Now: ' + currentTime);
                    
                    List<Elevated_Access_Request__c> earl = [SELECT Id 
                                                             FROM   Elevated_Access_Request__c
                                                             WHERE  From_Date__c <= :currentTime
                                                             AND    To_Date__c >= :currentTime
                                                             AND    For_User__c = :loginEvent.UserId
                                                             AND    Status__c = 'Access Provided'];
                    
                    if ( earl.size() > 0 ) {
                        System.Debug('Allowed Ear: ' + earl[0].Id);

                        // Check for high assurance session; If you are logging in with elevated access, you should have high assurance session
                        if ( loginEvent.SessionLevel != 'HIGH_ASSURANCE' ) {
                                return true;
                        }                       
                    } 
                    else {
                        return true;
                        
                    }
                    
            }
            
        }
        
        return false;  
    }
}